### ISSUE TITLE
P102 opcodes

### ISSUE THREAD

**Issue by Xordevv** [PsykoDev/Full-Opcode-Tera-EU-NA#12]
Hi, may we get an update please

**Comment by palvaloo** [comment]
Please, I would like as well!

**Comment by Leibeun** [comment]
yes pls, this update broke your fly forever and auto pet modules

**Comment by palvaloo** [comment]
We just need the updated opcodes for NA

**Comment by palvaloo** [comment]
> yes pls, this update broke your fly forever and auto pet modules

Btw for Fly forever, I was able to manually get the opcode for you:
S_CANT_FLY_ANYMORE 58792

**Comment by palvaloo** [comment]
he updated

**Comment by PsykoDev** [comment]
i don't want launch the game tell me if that work or not aight

**Comment by palvaloo** [comment]
it works, thank you very much!

**Comment by PsykoDev** [comment]
np sir

**Comment by palvaloo** [comment]
Is there a way to contact you on discord or something? I am learning coder and just have a question about code

**Comment by Xordevv** [comment]
@PsykoDev it works for me. Thank you very much!
